# Generated by Django 2.1.7 on 2019-02-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('detail_acount', models.CharField(max_length=150, verbose_name='Detai account')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Account number')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('identity_type', models.CharField(choices=[('DNI', 'DNI'), ('FOREIGN_CARD', 'FOREIGN_CARD')], max_length=150, verbose_name='Identity Type')),
                ('identity_num', models.CharField(max_length=15, verbose_name='Identity Num')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
