# Generated by Django 2.1.7 on 2019-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_father_name',
            field=models.CharField(default=2, max_length=150, verbose_name='Last Father Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_mother_name',
            field=models.CharField(default='21', max_length=150, verbose_name='Last Mother Name'),
            preserve_default=False,
        ),
    ]
