# Generated by Django 2.1.7 on 2019-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20190223_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='identity_num',
            field=models.CharField(default='33', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='identity_num',
            field=models.CharField(max_length=15, unique=True, verbose_name='Identity Num'),
        ),
    ]
