# Generated by Django 2.1.7 on 2019-02-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20190223_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
