# Generated by Django 2.1.7 on 2019-02-23 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_remove_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
